import type { CategoryKey } from "@core/models";
import {
  Baby,
  BadgeDollarSign,
  Bed,
  Bus,
  Camera,
  Castle,
  CloudSun,
  Coffee,
  Coins,
  Footprints,
  GraduationCap,
  Handshake,
  Heart,
  HeartPulse,
  Landmark,
  Languages,
  Leaf,
  Mountain,
  Music,
  Plane,
  Receipt,
  Rocket,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Smile,
  Stamp,
  Stethoscope,
  Theater,
  Trees,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  UsersRound,
  UtensilsCrossed,
  Waves,
  Wheat,
  Wifi,
} from "lucide-react";

/** Maps every CategoryKey to its Lucide icon component. */
export const CATEGORY_ICONS: Record<CategoryKey, typeof TrendingUp> = {
  economy: TrendingUp,
  affordability: Coins,
  foodSecurity: Wheat,
  healthcare: HeartPulse,
  education: GraduationCap,
  environment: Leaf,
  climate: CloudSun,
  safety: Shield,
  infrastructure: Wifi,
  happiness: Smile,
  humanDevelopment: Users,
  governance: Landmark,
  englishProficiency: Languages,
  digitalFreedom: ShieldCheck,
  personalFreedom: UserCheck,
  logistics: Truck,
  biodiversity: Trees,
  socialTolerance: Heart,
  taxFriendliness: Receipt,
  startupEnvironment: Rocket,
  airConnectivity: Plane,
  culturalHeritage: Theater,
  healthcareCost: Stethoscope,
  nomadCommunity: UsersRound,
  visaFriendliness: Stamp,
  costEfficiency: BadgeDollarSign,
  workLifeBalance: Coffee,
  digitalReadiness: Smartphone,
  culturalFit: Handshake,
  tourismSafety: Shield,
  accommodationCost: Bed,
  transportCost: Bus,
  tourismInfrastructure: Wifi,
  localFriendliness: Smile,
  nightlifeEntertainment: Music,
  touristScamSafety: ShieldAlert,
  streetFoodCuisine: UtensilsCrossed,
  beachWaterQuality: Waves,
  walkabilityScenicBeauty: Footprints,
  shoppingMarkets: ShoppingBag,
  photographySpots: Camera,
  familyFriendliness: Baby,
  adventureSports: Mountain,
  historicalSites: Castle,
};
